//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenSpace.Manage
{


    public partial class Khesarat
    {
        protected global::GreenSpace.Controls.CtlKhesarat CtlKhesarat1;
    }
}
